///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: music/m_intro.aks
/// Generation time: lun, 02 de dic de 2019 17:27:30
///

/// Song 'm_intro' metadata macros
#define m_intro_address  0x03CD
#define m_intro_size     322
#define m_intro_end      0x50e

/// Song 'm_intro' array declaration
extern void m_intro[m_intro_size];
